### ISSUE TITLE
Add following book to prepare

### ISSUE THREAD

**Issue by mikewo** [camassey/ConferenceClub#1]
File New Presentation
http://www.amazon.com/File-New-Presentation-Developers-Professionals-ebook/dp/B00GEH9FHM/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1414417789&sr=1-1&keywords=file+new+presentation

**Comment by camassey** [comment]
This looks like it covers pretty much the whole scope of creating a presentation - I think we need a specific "General Reading" category to the resource list.
